export {default  as Navbar} from './Navbar/Navbar'
export {default  as Header} from './Header/Header'
export {default  as Seaction} from './TopDestination/Seaction'
export {default  as ImageGrid} from './Hotel&Place/ImageGrid'
export {default  as Service} from './Service/Service'
export {default  as Banner} from './banner/Banner'
export {default  as TopBanner} from './TopBanner/TopBanner'
export {default  as Footer} from './Footer/Footer'
